using System.Reflection;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;

namespace Data.Database.SqlObjects;

public static class DatabaseSqlObjectsInstaller
{
    private static readonly string[] ScriptApplyOrder =
    [
        "base_utilities.sql",
        "accounts_functions.sql",
        "accounts_triggers.sql",
        "phase5_db_objects_up.sql",
        "licenses_functions.sql",
        "licenses_triggers.sql",
        "payments_functions.sql",
        "payments_triggers.sql"
    ];

    public static async Task ApplyAsync(ApplicationDbContext dbContext, CancellationToken cancellationToken = default)
    {
        // SQL object scripts are PostgreSQL-specific (functions/triggers/views/sequences).
        var providerName = dbContext.Database.ProviderName;
        if (providerName is null || !providerName.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            return;

        // Required by digest()/gen_random_uuid() used in DB functions and seeds.
        await ExecuteSqlScriptAsync(dbContext, "CREATE EXTENSION IF NOT EXISTS pgcrypto;", cancellationToken);
        // Reference DB exposes many gbt_* and *_dist helper functions from btree_gist.
        await ExecuteSqlScriptAsync(dbContext, "CREATE EXTENSION IF NOT EXISTS btree_gist;", cancellationToken);
        await EnsureLicenseSellableTablesAsync(dbContext, cancellationToken);

        foreach (var script in ScriptApplyOrder)
        {
            var sql = ReadEmbeddedSql(script);
            if (string.IsNullOrWhiteSpace(sql))
                continue;

            sql = NormalizeSql(sql);
            await ExecuteSqlScriptAsync(dbContext, sql, cancellationToken);
        }
    }

    private static string ReadEmbeddedSql(string fileName)
    {
        var assembly = typeof(DatabaseSqlObjectsInstaller).Assembly;
        var resourceName = $"Data.Migrations.Sql.{fileName}";
        using var stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded SQL resource not found: {resourceName}");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private static async Task ExecuteSqlScriptAsync(ApplicationDbContext dbContext, string sql, CancellationToken cancellationToken)
    {
        var strategy = dbContext.Database.CreateExecutionStrategy();
        await strategy.ExecuteAsync(async () =>
        {
            await using var transaction = await dbContext.Database.BeginTransactionAsync(cancellationToken);
            await using var command = dbContext.Database.GetDbConnection().CreateCommand();
            command.CommandText = sql;
            command.Transaction = transaction.GetDbTransaction();

            if (command.Connection?.State != System.Data.ConnectionState.Open)
                await command.Connection!.OpenAsync(cancellationToken);

            await command.ExecuteNonQueryAsync(cancellationToken);
            await transaction.CommitAsync(cancellationToken);
        });
    }

    private static string NormalizeSql(string sql)
    {
        // Ensure function blocks are statement-terminated.
        sql = Regex.Replace(sql, @"(?m)^\$function\$\s*$", "$function$;");

        // Make one-line trigger creation idempotent to support repeated startup execution.
        sql = Regex.Replace(
            sql,
            @"(?im)^\s*CREATE\s+TRIGGER\s+([a-zA-Z0-9_]+)\s+.*?\s+ON\s+([a-zA-Z0-9_.]+)\s+FOR\s+EACH\s+ROW\s+EXECUTE\s+FUNCTION\s+.*?;\s*$",
            m => $"DROP TRIGGER IF EXISTS {m.Groups[1].Value} ON {m.Groups[2].Value};{Environment.NewLine}{m.Value}");

        return sql;
    }

    private static Task EnsureLicenseSellableTablesAsync(ApplicationDbContext dbContext, CancellationToken cancellationToken)
    {
        // Some reference functions (licenses_*) depend on these tables but they may not exist
        // in fresh/reset environments before custom SQL object scripts are applied.
        const string sql = """
                           CREATE TABLE IF NOT EXISTS public.licenses_sellable (
                               id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               code varchar(64) NOT NULL,
                               name varchar(200) NOT NULL,
                               sellable_type varchar(32) NOT NULL,
                               module_id bigint NULL,
                               parent_sellable_id bigint NULL,
                               is_active boolean NOT NULL DEFAULT true,
                               is_default_in_plan boolean NOT NULL DEFAULT false,
                               is_visible_in_build_plan boolean NOT NULL DEFAULT true,
                               created_at timestamptz NOT NULL DEFAULT now(),
                               updated_at timestamptz NOT NULL DEFAULT now()
                           );

                           CREATE TABLE IF NOT EXISTS public.licenses_sellable_price (
                               id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               sellable_id bigint NOT NULL,
                               billing_cycle_id bigint NOT NULL,
                               price_amount numeric(18,2) NOT NULL DEFAULT 0,
                               currency_code char(3) NOT NULL DEFAULT 'IRR',
                               is_active boolean NOT NULL DEFAULT true,
                               created_at timestamptz NOT NULL DEFAULT now(),
                               updated_at timestamptz NOT NULL DEFAULT now()
                           );

                           CREATE TABLE IF NOT EXISTS public.licenses_sellable_dependency (
                               id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               sellable_id bigint NOT NULL,
                               required_sellable_id bigint NOT NULL,
                               created_at timestamptz NOT NULL DEFAULT now()
                           );

                           CREATE TABLE IF NOT EXISTS public.licenses_plan_sellable (
                               id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               plan_id bigint NOT NULL,
                               sellable_id bigint NOT NULL,
                               is_included boolean NOT NULL DEFAULT true,
                               created_at timestamptz NOT NULL DEFAULT now()
                           );

                           CREATE TABLE IF NOT EXISTS public.licenses_subscription_sellable (
                               id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               subscription_id bigint NOT NULL,
                               sellable_id bigint NOT NULL,
                               price_amount numeric(18,2) NOT NULL DEFAULT 0,
                               currency_code char(3) NOT NULL DEFAULT 'IRR',
                               created_at timestamptz NOT NULL DEFAULT now()
                           );
                           """;

        return ExecuteSqlScriptAsync(dbContext, sql, cancellationToken);
    }
}
